/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // root type
    author: string; // String!
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    date: number; // Int!
    genre: string; // String!
    id: number; // Int!
    title: string; // String!
  }
  Like: { // root type
    book: NexusGenRootTypes['Book']; // Book!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email: string; // String!
    id: number; // Int!
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Book: { // field return type
    author: string; // String!
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    date: number; // Int!
    genre: string; // String!
    id: number; // Int!
    likers: NexusGenRootTypes['User'][]; // [User!]!
    postedBy: NexusGenRootTypes['User'] | null; // User
    title: string; // String!
  }
  Like: { // field return type
    book: NexusGenRootTypes['Book']; // Book!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    createBook: NexusGenRootTypes['Book']; // Book!
    deleteBook: NexusGenRootTypes['Book']; // Book!
    like: NexusGenRootTypes['Like'] | null; // Like
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    updateBook: NexusGenRootTypes['Book']; // Book!
  }
  Query: { // field return type
    book: NexusGenRootTypes['Book'] | null; // Book
    books: NexusGenRootTypes['Book'][]; // [Book!]!
  }
  User: { // field return type
    books: NexusGenRootTypes['Book'][]; // [Book!]!
    email: string; // String!
    id: number; // Int!
    likes: NexusGenRootTypes['Book'][]; // [Book!]!
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Book: { // field return type name
    author: 'String'
    body: 'String'
    createdAt: 'DateTime'
    date: 'Int'
    genre: 'String'
    id: 'Int'
    likers: 'User'
    postedBy: 'User'
    title: 'String'
  }
  Like: { // field return type name
    book: 'Book'
    user: 'User'
  }
  Mutation: { // field return type name
    createBook: 'Book'
    deleteBook: 'Book'
    like: 'Like'
    login: 'AuthPayload'
    signup: 'AuthPayload'
    updateBook: 'Book'
  }
  Query: { // field return type name
    book: 'Book'
    books: 'Book'
  }
  User: { // field return type name
    books: 'Book'
    email: 'String'
    id: 'Int'
    likes: 'Book'
    password: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createBook: { // args
      author: string; // String!
      body: string; // String!
      date: number; // Int!
      genre: string; // String!
      title: string; // String!
    }
    deleteBook: { // args
      id: number; // Int!
    }
    like: { // args
      bookId: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    signup: { // args
      email: string; // String!
      password: string; // String!
      username: string; // String!
    }
    updateBook: { // args
      author?: string | null; // String
      body?: string | null; // String
      date?: number | null; // Int
      genre?: string | null; // String
      id: number; // Int!
      title?: string | null; // String
    }
  }
  Query: {
    book: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}